### ISSUE TITLE
Ambiguous composer.json

### ISSUE THREAD

**Issue by byankin** [dotfinal/soquiz#1]
В проекте два файла comoser.json/composer.lock

**Comment by dotfinal** [comment]
Это нечаянно. переходы не работают, их надо под апач настраивать самому.

**Comment by byankin** [comment]
Удали лишнее)

**Comment by dotfinal** [comment]
Проект перезаливать, видимо, будем. На апаче люди запустить не могут. В общем, как изначально я и хотел, надо будет у кого-нибудь на апаче поставить, а я потом подключусь

**Comment by byankin** [comment]
я запустил же)

**Comment by dotfinal** [comment]
ну вот и я запустил, а Леша сказал, что надо новый поставить)
